version: "2"
services:
  restmail:
    build: .
    ports:
      - 25:9025
      - 80:8080
    environment:
      - REDIS_HOST=redis
      - RCPT_TO_DOMAIN_WHITELIST=gruen.tech
    command: sh -c "npm run start"
  redis:
    image: redis
    container_name: redis
    ports: 
     - 6379:6379